version: '3'

services:
  app:
    build: 
      context: . #rootをどこにするか
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www/html/app
    environment:
      - CHOKIDAR_USEPOLLING=true #Reactのファイルを更新したときに常に監視状態にする
    command: sh -c 'cd app && npm start'
    